/* Autogenerated by MaKL - Sun Feb 13 15:28:09 CET 2011 */
/* Configure arguments: --crypto=cyassl --gnu_debug */

#ifndef _CONF_H_
#define _CONF_H_

#undef USE_OPENSSL

#undef LIBSCS_VERSION
#define LIBSCS_VERSION "0.0.0"

#undef LIBSCS_VERSION_MAJOR
#define LIBSCS_VERSION_MAJOR 0

#undef LIBSCS_VERSION_MINOR
#define LIBSCS_VERSION_MINOR 0

#undef LIBSCS_VERSION_TEENY
#define LIBSCS_VERSION_TEENY 0

#undef OS_DARWIN
#define OS_DARWIN 1

#undef USE_CYASSL
#define USE_CYASSL 1

#undef HAVE_LIBZ
#define HAVE_LIBZ 1

#undef HAVE_LIBOPENSSL
#define HAVE_LIBOPENSSL 1

#undef HAVE_LIBCYASSL
#define HAVE_LIBCYASSL 1

#undef DESTDIR
#define DESTDIR "/usr/local"

#undef BINDIR
#define BINDIR "/usr/local/bin"

#undef SBINDIR
#define SBINDIR "/usr/local/sbin"

#undef CONFDIR
#define CONFDIR "/usr/local/etc"

#undef INCDIR
#define INCDIR "/usr/local/include"

#undef LIBDIR
#define LIBDIR "/usr/local/lib"

#undef SHLIBDIR
#define SHLIBDIR "/usr/local/lib"

#undef LIBEXDIR
#define LIBEXDIR "/usr/local/libexec"

#undef VARDIR
#define VARDIR "/usr/local/var"

#undef SHAREDIR
#define SHAREDIR "/usr/local/share"

#undef MANDIR
#define MANDIR "/usr/local/share/man"

#undef DOCDIR
#define DOCDIR "/usr/local/share/doc"

#endif /* !_CONF_H_ */
